### ISSUE TITLE
Random Glow Color 

### ISSUE THREAD

**Issue by Atmosfera1337** [Stewart-Anubis/Zr-Leader-Ultimate#1]
Is it possible to make a random glow color?

I don't understand SM code so I don't know how.

**Comment by Stewart-Anubis** [comment]
It would be ok, but the brightness system is applied only once by the plugin, not being the same as the beacon. Adding a color change system would add more processing and more delay to the server.
It would be possible to make each round a different fixed color, but I think that would be irrelevant.
